name = input("이름을 입력하세요: ")
id = input("학번을 입력하세요: ")
major = input("학과를 입력하세요: ")
school = input("학교를 입력하세요: ")
print("")
print("<출력>")
print(f"이름 : {name}")
print(f"학번 : {id}")
print(f"학과 : {major}")
print(f"학교 : {school}")